import type { RuntimeApprovalAuditRecord, RuntimeRevisionRecord, RuntimeReviewTaskRecord } from "../../app/platform/desktopGateway.js";

interface ReviewInspectorProps { warnings: string[]; reviewTasks: RuntimeReviewTaskRecord[]; revisions: RuntimeRevisionRecord[]; approvalAudit: RuntimeApprovalAuditRecord[]; selectedTaskIndex: number; onSelectTask(index: number): void; }

export function ReviewInspector({ warnings, reviewTasks, revisions, approvalAudit, selectedTaskIndex, onSelectTask }: ReviewInspectorProps) {
  return <div className="review-inspector-sections">
    <section className="review-inspector-section"><div className="review-section-heading"><strong>Review Queue</strong><span>{reviewTasks.length}</span></div><div className="review-task-list">{reviewTasks.length === 0 ? <div className="empty-copy">No active review tasks.</div> : reviewTasks.map((task, index) => <button key={task.review_task_id} onClick={() => onSelectTask(index)} className={`review-task${index === selectedTaskIndex ? " review-task--selected" : ""}`}><strong>{task.review_task_id}</strong><small>{task.reason_codes.join(", ")} · {task.status}</small></button>)}</div></section>
    <section className="review-inspector-section"><div className="review-section-heading"><strong>Warnings</strong><span>{warnings.length}</span></div><div className="compact-event-list">{warnings.map((warning) => <div className="compact-event compact-event--warning" key={warning}>{warning}</div>)}</div></section>
    <section className="review-inspector-section"><div className="review-section-heading"><strong>Revisions</strong><span>{revisions.length}</span></div><div className="compact-event-list">{revisions.length === 0 ? <div className="empty-copy">No revisions yet.</div> : revisions.map((revision) => <div className="compact-event" key={revision.revision_id}><strong>{revision.summary}</strong><small>{revision.before_value ?? "—"} → {revision.after_value ?? "—"}</small></div>)}</div></section>
    <section className="review-inspector-section"><div className="review-section-heading"><strong>Approval Audit</strong><span>{approvalAudit.length}</span></div><div className="compact-event-list">{approvalAudit.length === 0 ? <div className="empty-copy">No approval events yet.</div> : approvalAudit.map((record) => <div className="compact-event" key={record.approval_id}><strong>{record.action}</strong><small>{record.actor} · {record.created_at}</small></div>)}</div></section>
  </div>;
}
